### PR TITLE
Feature/lidar

### PR DESCRIPTION
**Pull request by feinxcookies**

### CODE REVIEW

**Review by notdom2078 — COMMENTED** [review]
Looks good from my end

**Comment by feinxcookies** [comment]
algorithm really needs too be improved but works for advanced 1 and beginner 1

**Comment by feinxcookies** [comment]
oops closed instead of merging anything :")

**Review by sliawyer — CHANGES_REQUESTED** [review]
Lidar Controller needs to be put into its own controller folder before merging in. Otherwise it will overwrite the beginner track controller

**Pull request closed without merging**
